language: haskell

ghc:
    - 7.4
    - 7.6
    - 7.8

install:
    - sudo apt-get -q -y install hlint
    - cabal install --only-dependencies --enable-tests
    - cabal configure --enable-tests
    - cabal build

script:
    - cabal test && hlint Control test

