language: haskell

install:
    - sudo apt-get -q -y install hlint
    - cabal install --only-dependencies
    - cabal configure -fWerror --enable-tests
    - cabal build

script:
    - cabal test && hlint Control test

